# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bid_pb2 as bid__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BidServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuctionStarted = channel.unary_unary(
                '/BidService/AuctionStarted',
                request_serializer=bid__pb2.AuctionEventRequest.SerializeToString,
                response_deserializer=bid__pb2.AuctionEventAck.FromString,
                _registered_method=True)
        self.AuctionClosed = channel.unary_unary(
                '/BidService/AuctionClosed',
                request_serializer=bid__pb2.AuctionEventRequest.SerializeToString,
                response_deserializer=bid__pb2.AuctionClosedResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/BidService/PlaceBid',
                request_serializer=bid__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=bid__pb2.PlaceBidResponse.FromString,
                _registered_method=True)


class BidServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuctionStarted(self, request, context):
        """Called when an auction becomes active
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuctionClosed(self, request, context):
        """Called when an auction is closed; returns winner (if any)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Called by clients to place a bid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuctionStarted': grpc.unary_unary_rpc_method_handler(
                    servicer.AuctionStarted,
                    request_deserializer=bid__pb2.AuctionEventRequest.FromString,
                    response_serializer=bid__pb2.AuctionEventAck.SerializeToString,
            ),
            'AuctionClosed': grpc.unary_unary_rpc_method_handler(
                    servicer.AuctionClosed,
                    request_deserializer=bid__pb2.AuctionEventRequest.FromString,
                    response_serializer=bid__pb2.AuctionClosedResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=bid__pb2.PlaceBidRequest.FromString,
                    response_serializer=bid__pb2.PlaceBidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BidService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BidService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuctionStarted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BidService/AuctionStarted',
            bid__pb2.AuctionEventRequest.SerializeToString,
            bid__pb2.AuctionEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuctionClosed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BidService/AuctionClosed',
            bid__pb2.AuctionEventRequest.SerializeToString,
            bid__pb2.AuctionClosedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BidService/PlaceBid',
            bid__pb2.PlaceBidRequest.SerializeToString,
            bid__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
