# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbid.proto\")\n\x13\x41uctionEventRequest\x12\x12\n\nauction_id\x18\x01 \x01(\x05\"3\n\x0f\x41uctionEventAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"a\n\x15\x41uctionClosedResponse\x12\x12\n\nauction_id\x18\x01 \x01(\x05\x12\x12\n\nhas_winner\x18\x02 \x01(\x08\x12\x11\n\twinner_id\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\"F\n\x0fPlaceBidRequest\x12\x12\n\nauction_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"i\n\x10PlaceBidResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nauction_id\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\x32\xb6\x01\n\nBidService\x12\x38\n\x0e\x41uctionStarted\x12\x14.AuctionEventRequest\x1a\x10.AuctionEventAck\x12=\n\rAuctionClosed\x12\x14.AuctionEventRequest\x1a\x16.AuctionClosedResponse\x12/\n\x08PlaceBid\x12\x10.PlaceBidRequest\x1a\x11.PlaceBidResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUCTIONEVENTREQUEST']._serialized_start=13
  _globals['_AUCTIONEVENTREQUEST']._serialized_end=54
  _globals['_AUCTIONEVENTACK']._serialized_start=56
  _globals['_AUCTIONEVENTACK']._serialized_end=107
  _globals['_AUCTIONCLOSEDRESPONSE']._serialized_start=109
  _globals['_AUCTIONCLOSEDRESPONSE']._serialized_end=206
  _globals['_PLACEBIDREQUEST']._serialized_start=208
  _globals['_PLACEBIDREQUEST']._serialized_end=278
  _globals['_PLACEBIDRESPONSE']._serialized_start=280
  _globals['_PLACEBIDRESPONSE']._serialized_end=385
  _globals['_BIDSERVICE']._serialized_start=388
  _globals['_BIDSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
