# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auction_pb2 as auction__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAuction = channel.unary_unary(
                '/auction.AuctionService/CreateAuction',
                request_serializer=auction__pb2.CreateAuctionRequest.SerializeToString,
                response_deserializer=auction__pb2.Auction.FromString,
                _registered_method=True)
        self.ListAuctions = channel.unary_unary(
                '/auction.AuctionService/ListAuctions',
                request_serializer=auction__pb2.ListAuctionsRequest.SerializeToString,
                response_deserializer=auction__pb2.ListAuctionsResponse.FromString,
                _registered_method=True)
        self.GetAuction = channel.unary_unary(
                '/auction.AuctionService/GetAuction',
                request_serializer=auction__pb2.GetAuctionRequest.SerializeToString,
                response_deserializer=auction__pb2.GetAuctionResponse.FromString,
                _registered_method=True)


class AuctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuctions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuction,
                    request_deserializer=auction__pb2.CreateAuctionRequest.FromString,
                    response_serializer=auction__pb2.Auction.SerializeToString,
            ),
            'ListAuctions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuctions,
                    request_deserializer=auction__pb2.ListAuctionsRequest.FromString,
                    response_serializer=auction__pb2.ListAuctionsResponse.SerializeToString,
            ),
            'GetAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuction,
                    request_deserializer=auction__pb2.GetAuctionRequest.FromString,
                    response_serializer=auction__pb2.GetAuctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.AuctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auction.AuctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/CreateAuction',
            auction__pb2.CreateAuctionRequest.SerializeToString,
            auction__pb2.Auction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/ListAuctions',
            auction__pb2.ListAuctionsRequest.SerializeToString,
            auction__pb2.ListAuctionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionService/GetAuction',
            auction__pb2.GetAuctionRequest.SerializeToString,
            auction__pb2.GetAuctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuctionCallbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnAuctionStarted = channel.unary_unary(
                '/auction.AuctionCallbackService/OnAuctionStarted',
                request_serializer=auction__pb2.AuctionStartedNotification.SerializeToString,
                response_deserializer=auction__pb2.AuctionEventAck.FromString,
                _registered_method=True)
        self.OnAuctionClosed = channel.unary_unary(
                '/auction.AuctionCallbackService/OnAuctionClosed',
                request_serializer=auction__pb2.AuctionClosedNotification.SerializeToString,
                response_deserializer=auction__pb2.AuctionEventAck.FromString,
                _registered_method=True)


class AuctionCallbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnAuctionStarted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnAuctionClosed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuctionCallbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnAuctionStarted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnAuctionStarted,
                    request_deserializer=auction__pb2.AuctionStartedNotification.FromString,
                    response_serializer=auction__pb2.AuctionEventAck.SerializeToString,
            ),
            'OnAuctionClosed': grpc.unary_unary_rpc_method_handler(
                    servicer.OnAuctionClosed,
                    request_deserializer=auction__pb2.AuctionClosedNotification.FromString,
                    response_serializer=auction__pb2.AuctionEventAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auction.AuctionCallbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auction.AuctionCallbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuctionCallbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnAuctionStarted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionCallbackService/OnAuctionStarted',
            auction__pb2.AuctionStartedNotification.SerializeToString,
            auction__pb2.AuctionEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnAuctionClosed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auction.AuctionCallbackService/OnAuctionClosed',
            auction__pb2.AuctionClosedNotification.SerializeToString,
            auction__pb2.AuctionEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
