# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auction_pb2 as auction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbid.proto\x12\x03\x62id\x1a\rauction.proto\")\n\x13\x41uctionEventRequest\x12\x12\n\nauction_id\x18\x01 \x01(\x05\"a\n\x15\x41uctionClosedResponse\x12\x12\n\nauction_id\x18\x01 \x01(\x05\x12\x12\n\nhas_winner\x18\x02 \x01(\x08\x12\x11\n\twinner_id\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\"F\n\x0fPlaceBidRequest\x12\x12\n\nauction_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"i\n\x10PlaceBidResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nauction_id\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\"\x8f\x01\n\x17PaymentLinkNotification\x12\x12\n\nauction_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x14\n\x0cpayment_link\x18\x03 \x01(\t\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\r\n\x05value\x18\x06 \x01(\x01\"/\n\x0b\x42idEventAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd2\x01\n\nBidService\x12\x44\n\x0e\x41uctionStarted\x12\x18.bid.AuctionEventRequest\x1a\x18.auction.AuctionEventAck\x12\x45\n\rAuctionClosed\x12\x18.bid.AuctionEventRequest\x1a\x1a.bid.AuctionClosedResponse\x12\x37\n\x08PlaceBid\x12\x14.bid.PlaceBidRequest\x1a\x15.bid.PlaceBidResponse2^\n\x12\x42idCallbackService\x12H\n\x16OnPaymentLinkGenerated\x12\x1c.bid.PaymentLinkNotification\x1a\x10.bid.BidEventAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUCTIONEVENTREQUEST']._serialized_start=33
  _globals['_AUCTIONEVENTREQUEST']._serialized_end=74
  _globals['_AUCTIONCLOSEDRESPONSE']._serialized_start=76
  _globals['_AUCTIONCLOSEDRESPONSE']._serialized_end=173
  _globals['_PLACEBIDREQUEST']._serialized_start=175
  _globals['_PLACEBIDREQUEST']._serialized_end=245
  _globals['_PLACEBIDRESPONSE']._serialized_start=247
  _globals['_PLACEBIDRESPONSE']._serialized_end=352
  _globals['_PAYMENTLINKNOTIFICATION']._serialized_start=355
  _globals['_PAYMENTLINKNOTIFICATION']._serialized_end=498
  _globals['_BIDEVENTACK']._serialized_start=500
  _globals['_BIDEVENTACK']._serialized_end=547
  _globals['_BIDSERVICE']._serialized_start=550
  _globals['_BIDSERVICE']._serialized_end=760
  _globals['_BIDCALLBACKSERVICE']._serialized_start=762
  _globals['_BIDCALLBACKSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
