# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAuctionWinner = channel.unary_unary(
                '/payment.PaymentService/ProcessAuctionWinner',
                request_serializer=payment__pb2.AuctionWinnerRequest.SerializeToString,
                response_deserializer=payment__pb2.PaymentLinkResponse.FromString,
                _registered_method=True)
        self.UpdatePaymentStatus = channel.unary_unary(
                '/payment.PaymentService/UpdatePaymentStatus',
                request_serializer=payment__pb2.PaymentStatusUpdate.SerializeToString,
                response_deserializer=payment__pb2.PaymentStatusAck.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessAuctionWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePaymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAuctionWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAuctionWinner,
                    request_deserializer=payment__pb2.AuctionWinnerRequest.FromString,
                    response_serializer=payment__pb2.PaymentLinkResponse.SerializeToString,
            ),
            'UpdatePaymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePaymentStatus,
                    request_deserializer=payment__pb2.PaymentStatusUpdate.FromString,
                    response_serializer=payment__pb2.PaymentStatusAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessAuctionWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ProcessAuctionWinner',
            payment__pb2.AuctionWinnerRequest.SerializeToString,
            payment__pb2.PaymentLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePaymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/UpdatePaymentStatus',
            payment__pb2.PaymentStatusUpdate.SerializeToString,
            payment__pb2.PaymentStatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PaymentNotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnPaymentLinkCreated = channel.unary_unary(
                '/payment.PaymentNotificationService/OnPaymentLinkCreated',
                request_serializer=payment__pb2.PaymentLinkNotification.SerializeToString,
                response_deserializer=payment__pb2.NotificationAck.FromString,
                _registered_method=True)
        self.OnPaymentStatusChanged = channel.unary_unary(
                '/payment.PaymentNotificationService/OnPaymentStatusChanged',
                request_serializer=payment__pb2.PaymentStatusNotification.SerializeToString,
                response_deserializer=payment__pb2.NotificationAck.FromString,
                _registered_method=True)


class PaymentNotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnPaymentLinkCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPaymentStatusChanged(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentNotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnPaymentLinkCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPaymentLinkCreated,
                    request_deserializer=payment__pb2.PaymentLinkNotification.FromString,
                    response_serializer=payment__pb2.NotificationAck.SerializeToString,
            ),
            'OnPaymentStatusChanged': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPaymentStatusChanged,
                    request_deserializer=payment__pb2.PaymentStatusNotification.FromString,
                    response_serializer=payment__pb2.NotificationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentNotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentNotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentNotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnPaymentLinkCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentNotificationService/OnPaymentLinkCreated',
            payment__pb2.PaymentLinkNotification.SerializeToString,
            payment__pb2.NotificationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPaymentStatusChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentNotificationService/OnPaymentStatusChanged',
            payment__pb2.PaymentStatusNotification.SerializeToString,
            payment__pb2.NotificationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
